#!/bin/sh

ENV_FILE_PATH='/usr/share/nginx/html/.env'
echo `echo REACT_APP_GNMT_ADAPTER_TRANSLATE_ENDPOINT`=$REACT_APP_GNMT_ADAPTER_TRANSLATE_ENDPOINT >  $ENV_FILE_PATH
echo `echo REACT_APP_GNMT_ADAPTER_HOST=$REACT_APP_GNMT_ADAPTER_HOST`  >>  $ENV_FILE_PATH
echo `echo REACT_APP_AAI4B_NMT_HOST=$REACT_APP_AAI4B_NMT_HOST`  >>  $ENV_FILE_PATH
echo `echo REACT_APP_AAIB_NMT_TRANSLATE_ENDPOINT=$REACT_APP_AAIB_NMT_TRANSLATE_ENDPOINT` >> $ENV_FILE_PATH
echo `echo REACT_APP_NMT_TRANSLATE_ENDPOINT=$REACT_APP_NMT_TRANSLATE_ENDPOINT`  >> $ENV_FILE_PATH
echo `echo REACT_APP_NMT_HOST=$REACT_APP_NMT_HOST` >> $ENV_FILE_PATH
echo `echo REACT_APP_APIGW_BASE_URL=$REACT_APP_APIGW_BASE_URL` >> $ENV_FILE_PATH
echo `echo REACT_APP_DOWNLOAD_URL=$REACT_APP_DOWNLOAD_URL` >> $ENV_FILE_PATH
echo `echo REACT_APP_CLIENT_ID=$REACT_APP_CLIENT_ID`  >> $ENV_FILE_PATH