#!groovy
node('server_build_slave') {

try {

   stage('Checkout'){

      checkout scm
   }
stage('compress build folder')
withCredentials([usernamePassword(credentialsId: 'anuvaad-docker-hub-credentials', passwordVariable: 'dockerhub_pass', usernameVariable: 'dockerhub_user')])
{
sh '''
cd anuvaad-fe/anuvaad-webapp
if [ -f "$(pwd)/build" ]
then
  rm -f $(pwd)/build
fi

if [  $( docker ps -q -f status=exited --filter "name=$JOB_BASE_NAME" ) ]
then
docker rm "$JOB_BASE_NAME"
fi

docker run --env REACT_APP_BASE_URL=$base_url --env REACT_APP_APIGW_BASE_URL=$apigw_url --env REACT_APP_DOWNLOAD_URL=$download_url --env REACT_APP_CLIENT_ID=$client_id -v $(pwd):/opt --name "$JOB_BASE_NAME" node:12.18.4-slim /bin/sh -c "npm -g install npm@^6.14.8 && cd /opt && mkdir -p /usr/share/man/man1mkdir -p /usr/share/man/man1 && apt update && apt install -y python3 openjdk-8-jdk && rm -rf package-lock.json && npm install &&  npm run build"
docker rm "$JOB_BASE_NAME"
commit_id=$(git rev-parse --short HEAD)
echo $commit_id> commit_id.txt
docker build -t anuvaadio/$image_name:$commit_id .
docker login -u $dockerhub_user -p $dockerhub_pass
docker push anuvaadio/$image_name:$commit_id

'''

        }


}

catch (err) {
    currentBuild.result = "FAILURE"
    throw err
 }



}