FROM openjdk:8
ADD anuvaad-api/anuvaad-dashboard/analytics-service/target/analytics-0.0.1-SNAPSHOT.jar analytics-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/analytics-0.0.1-SNAPSHOT.jar"]
EXPOSE 8089
