from .sentence import SaveSentenceResource, FetchSentenceResource, SentenceStatisticsCount, GetSentencesResource
from .file_content import FileContentGetResource, FileContentSaveResource, FileContentUpdateResource, FileContentStoreReference, FileContentGetReference
from .word import WordSaveResource, WordSearch