from .sentence import SaveSentenceResource, FetchSentenceResource, SentenceStatisticsCount, GetSentencesResource
from .file_content import FileContentGetResource, FileContentSaveResource, FileContentUpdateResource, FileContentStoreReference, FileContentGetReference, FileContentGetV1Resource
from .word import WordSaveResource, WordSearch