swagger: "2.0"
info:
  version: 1.0.0
  title: Anuvaad document processing pipeline APIs
  description: The specification defines various modules that participate in the orchestration of document processing flow. The document processing leverages various CV technique to achieve the desired results.
  contact:
    name: KD, Dhiraj, Naresh
    email: kumar.deepak@tarento.com

schemes:
  - https
basePath: '/document-processor'

paths:
  /layout-detector/v0/prima/process:
    post:
      summary: The method extracts the layouts present in the page of the given file using PrimaLayNet model
      parameters:
        - name: filename
          in: body
          required: true
          schema:
            $ref: '#/definitions/LayoutDetectorRequest'
      tags:
      - Layout Detector
      responses:
        200:
          description: On successful completion of the job.
          schema:
            $ref: '#/definitions/HttpOutputSuccess'
        400:
          description: On errors causing a failure in the job.
          schema:
            $ref: '#/definitions/HttpOutputError'
        
definitions:

  LayoutDetectorRequest:
    type: object
    properties:
      inputs:
        type: array
        description: array of files and pages 
        items:
          type: string
          $ref: '#/definitions/LayoutDetectorInput'
          
  LayoutDetectorResponse:
    type: object
    properties:
      inputs:
        type: array
        description: array of files and pages
        items:
          $ref: '#/definitions/LayoutDetectorInput'
      outputs:
        type: array
        description: array of regions after layout analysis
        items:
          $ref: '#/definitions/LayoutDetectorOutput'
    required:
      - outputs
          
  LayoutDetectorOutput:
    type: object
    properties:
      file:
        type: object
        description: file object that is received for processing
        $ref: '#/definitions/File'
      pages:
        type: array
        description: pages present in the file
        items:
          $ref: '#/definitions/Page'
      status:
        type: object
        description: operation result for the file that is processed
        $ref: '#/definitions/ErrorCode'
      
  LayoutDetectorInput:
    type: object
    properties:
      file:
        type: object
        description: file object on which configuration will be applied for processing
        $ref: '#/definitions/File'
      config:
        type: object
        description: detection configuration parameters that will be applied on the file
        $ref: '#/definitions/DetectConfig'
      pages:
        type: array
        description: list of page object
        items:
          $ref: '#/definitions/Page'
      page_info:
        type: array
        description: list of page metadata
        items:
          type: string
    required:
      - file
      - config
      - pages
      - page_info
  
  File:
    type: object
    properties:
      identifier:
        type: string
        description: unique identifier, uuid-v4
      name:
        type: string
        description: human readable name of file
      format:
        type: string
        description: allowed file format
        enum: ['PDF', 'PNG', 'JPEG', 'BMP']
  
  OCR:
    type: object
    properties:
      option:
        type: string
        description: ocr configuration settings
        enum: ['HIGH_ACCURACY', 'MEDIUM_ACCURACY', 'LOW_ACCURACY']
      language:
        type: string
        description: indic language code as per ISO 639-1
        enum: ['hi','ma','ta', 'ml', 'ka']
  
  DetectConfig:
    type: object
    properties:
      OCR:
        type: object
        $ref: '#/definitions/OCR'
  
  Point:
    type: object
    properties:
      x:
        type: integer
        description: x-coordinate
      y:
        type: integer
        description: y-coordinate
      confidence:
        type: number
        description: detection confidence
    required:
      - x
      - y
      - confidence
  
  Polygon:
    type: object
    properties:
      vertices:
        type: array
        description: polygon that is enclosing the identification area
        items:
          $ref: '#/definitions/Point'
        
  Font:
    type: object
    properties:
      family:
        type: string
        description: font family
      size:
        type: number
        description: font size
      style:
        type: string
        description: font style like BOLD, ITALIC, REGULAR
        enum: ['BOLD', "ITALIC", 'REGULAR']
  
  Line:
    type: object
    description: a group of related words
    properties:
      identifier:
        type: string
        description: unique identifier, uuidv4
        format: uuid
      boundingBox:
        type: object
        description: positional information of bounding box
        $ref: '#/definitions/Polygon'
      font:
        type: object
        description: font property
        $ref: '#/definitions/Font'
        
  Word:
    type: object
    description: a language script that can be written together and generates a meaning
    properties:
      identifier:
        type: string
        description: word level identifier
        format: uuid
      boundingBox:
        type: object
        description: positional information of bounding box
        $ref: '#/definitions/Polygon'
      class:
        type: string
        description: though not grammatical however used extensively in document writings
        enum: ['SUPERSCRIPT', 'SUBSCRIPT']
      text:
        type: string
        description: the textual payload
      language:
        type: string
        description: indic language code as per ISO 639-1
        enum: ['hi','ma','ta', 'ml', 'ka']
      confidence:
        type: number
        description: detectiong confidence
    required:
      - identifier
      - boundingBox
        
  Region:
    type: object
    description: the group of related lines object
    properties:
      identifier:
        type: string
        description: unique identifier, uuidv4
        format: uuid
      boundingBox:
        type: object
        description: positional information of bounding box
        $ref: '#/definitions/Polygon'
      class:
        type: string
        description: category of block
        enum: ['LINE', 'HEADER', 'FOOTER', 'FOOTNOTE', 'TABLE', 'IMAGE', 'BULLETS', 'BACKGROUND']
    required:
      - identifier
      - boundingBox

  Page:
    type: object
    properties:
      identifier:
        type: string
        description: page identifier
        format: uuid
      vertices:
        type: object
        description: positional information of bounding box
        $ref: '#/definitions/Polygon'
      resolution:
        type: number
        description: resolution of page image
      regions:
        type: array
        description: list of region present in a page
        items:
          $ref: '#/definitions/Region'
      lines:
        type: array
        description: list of lines present in a page
        items:
          $ref: '#/definitions/Line'
      words:
        type: array
        description: list of words present in a page
        items:
          $ref: '#/definitions/Word'
    required:
      - identifier
      - vertices
      - resolution
  
  ErrorCode:
    type: object
    properties:
      code:
        type: integer
        description: status code
      message:
        type: string
        description: human understandable format
    required:
      - code
      - message
  
  HttpOutputSuccess:
    type: object
    properties:
      ok:
        type: boolean
        description: request successful indicator.
      why:
        type: string
        description: Response message.
      status:
        type: object
        description: overall operation status
      data:
        type: object
        description: the return value should be returned under this property
        $ref: '#/definitions/LayoutDetectorResponse'

  HttpOutputError:
    type: object
    properties:
      ok:
        type: boolean
        description: request successful indicator.
      why:
        type: string
        description: Response message.
      status:
        type: object
        description: overall operation status
        $ref: '#/definitions/ErrorCode'
      data:
        type: integer
        description: should be null object
        default: null
        
responses:
  ERROR_MISSING_MANDATORY_PARAMETERS:
    description: Input request does not have parameters are the required.
    schema:
      $ref: '#/definitions/ErrorCode'
  ERROR_UNAUTHORIZED:
    description: request does not have relevant authority to start the process.
    schema:
      $ref: '#/definitions/ErrorCode'
  ERROR_INVALID_FILE_FORMAT:
    description: provided file data is invalid, choose from the given list
    schema:
      $ref: '#/definitions/ErrorCode'
  ERROR_WORD_DETECTION:
    description: model detected error while executing its purpose
    schema:
      $ref: '#/definitions/ErrorCode'
  ERROR_RESOURCE_EXHAUSTED:
    description: application deprived of system resources
    schema:
      $ref: '#/definitions/ErrorCode'
  SUCCESS:
    description: all good
    schema:
      $ref: '#/definitions/ErrorCode'
