const sentence_actions = {
    SENTENCE_MERGED: 'SENTENCE_MERGED',
    SENTENCE_SPLITTED: 'SENTENCE_SPLITTED',
    SENTENCE_SAVED: 'SENTENCE_SAVED',
    START_MODE_MERGE: 'START_MODE_MERGE',
    END_MODE_MERGE: 'END_MODE_MERGE',
    SENTENCE_SOURCE_EDITED: 'SENTENCE_SOURCE_EDITED'
};
export default  sentence_actions;