const sentence_actions = {
    SENTENCE_MERGED: 'SENTENCE_MERGED',
    SENTENCE_SPLITTED: 'SENTENCE_SPLITTED',
    SENTENCE_SAVED: 'SENTENCE_SAVED',
    SENTENCE_SOURCE_EDITED: 'SENTENCE_SOURCE_EDITED'
};
export default  sentence_actions;