from .translate import InteractiveTranslateResource, InteractiveMultiTranslateResource, OpenNMTTranslateResource,InteractiveMultiTranslateResourceNew,NMTTranslateResource
from .model_convert import ModelConvertResource
from .labse_aligner import LabseAlignerResource
from .fetch_models import FetchModelsResource
from .performance import BatchNMTPerformanceResource
from .health import HealthResource