import logging
import os

# Flask server
DEBUG = False
context_path = '/anuvaad-etl/file-translator'
HOST = '0.0.0.0'
PORT = 5001
ENABLE_CORS = False

# REDIS
redis_server_host = os.environ.get('REDIS_URL', 'localhost')
redis_server_port = os.environ.get('REDIS_PORT', 6379)
redis_key_prefix = 'FT-'
redis_db = os.environ.get('ANUVAAD_FT_REDIS_DB', 4)

# MONGO DB
mongo_server_host = os.environ.get('MONGO_CLUSTER_URL', 'mongodb://localhost:27017,localhost:27018/?replicaSet=foo')

# kafka
consumer_grp_default = 'anuvaad-etl-file-translator-consumer-group'
consumer_grp_identifier = 'KAFKA_ANUVAAD_ETL_FILE_TRANLATOR_CONSUMER_GRP'
CONSUMER_GROUP = os.environ.get(consumer_grp_identifier, consumer_grp_default)

# For Transform flow
input_topic_default = 'anuvaad-dp-tools-file-translator-transform-input-v1'
input_topic_identifier = 'KAFKA_ANUVAAD_DP_TOOLS_FT_INPUT'
transform_input_topic = os.environ.get(input_topic_identifier, input_topic_default)

output_topic_default = 'anuvaad-dp-tools-file-translator-transform-output-v1'
output_topic_identifier = 'KAFKA_ANUVAAD_DP_TOOLS_FT_OUTPUT'
transform_output_topic = os.environ.get(output_topic_identifier, output_topic_default)

# For download flow
input_topic_default = 'anuvaad-dp-tools-file-translator-download-input-v1'
input_topic_identifier = 'KAFKA_ANUVAAD_DP_TOOLS_FT_DOWNLOAD_INPUT'
download_input_topic = os.environ.get(input_topic_identifier, input_topic_default)

output_topic_default = 'anuvaad-dp-tools-file-translator-download-output-v1'
output_topic_identifier = 'KAFKA_ANUVAAD_DP_TOOLS_FT_DOWNLOAD_OUTPUT'
download_output_topic = os.environ.get(output_topic_identifier, output_topic_default)

kf_local_server = 'localhost:9092'
kafka_ip_host = 'KAFKA_BOOTSTRAP_SERVER_HOST'
bootstrap_server = os.environ.get(kafka_ip_host, kf_local_server)

# Content Handler
FETCH_CONTENT_URL_DEFAULT = 'https://auth.anuvaad.org/'
FETCH_CONTENT_URL_VAR = 'CONTENT_HANDLER_URL'
CH_URL = os.environ.get(FETCH_CONTENT_URL_VAR, FETCH_CONTENT_URL_DEFAULT)

FETCH_CONTENT_ENDPOINT = 'anuvaad/content-handler/v0/fetch-content'
REF_LINK_STORE_ENDPOINT = 'anuvaad/content-handler/v0/ref-link/store'

# ENV HOST
ENV_HOST_URL = 'https://auth.anuvaad.org/'

# folders and file path
download_folder = 'upload'

# TIMEOUT
PDF_TO_HTML_TIMEOUT = 300
PDF_CONVERSION_TIMEOUT = 300

# DOCX CONFIG
DOCX_PARAGRAPH_GEN = True
DOCX_TABLE_DATA_GEN = True
DOCX_TOC_GEN = True
DOCX_HEADER_FOOTER_GEN = False
DOCX_TXT_BOX_CONTENT_GEN = True

DOCX_PARAGRAPH_TRANS = True
DOCX_TABLE_DATA_TRANS = True
DOCX_TABLE_OF_CONTENT_TRANS = True
DOCX_HEADER_FOOTER_TRANS = False
DOCX_TXT_BOX_CONTENT_TRANS = True

DOCX_HYPERLINK_SUPPORT = False
DOCX_FONT_VALIDATION_ENABLED = True

#FILE NAME
DOCX_DOCUMENT_XML = 'document.xml'
DOCX_STYLE_XML = 'style.xml'



# TOOL NAMES
TOOL_LIBRE = 'LIBRE'
TOOL_PDF_TO_HTML = 'PDFTOHTML'
TOOL_PYDOCX = 'PYDOCX'

# FILE TYPES
TYPE_DOCX = 'DOCX'
TYPE_PPTX = 'PPTX'
TYPE_PDF = 'PDF'
TYPE_HTML = 'HTML'

# LOCALE
LOCALE_ENGLISH = 'en'


# FLOWS
# FLOWS: DOCX
FLOW_DOCX_LIBRE_PDF_PDFTOHTML_HTML_S3_ENABLED = False
FLOW_DOCX_LIBREHTML_S3_ENABLED = False
FLOW_DOCX_PYDOCXHTML_S3_ENABLED = False
FLOW_DOCX_LIBREHTML_LIBREPDF_PDFTOHTML_HTML_S3_ENABLED = True
# FLOWS: PPTX
FLOW_PPTX_LIBRE_PDF_PDFTOHTML_HTML_S3_ENABLED = True
FLOW_PPTX_LIBRE_PDF_S3_ENABLED = False

# PAGE LIMIT
DOCX_PAGE_LIMIT_ENABLE = True
PARA_WISE_PAGE_LIMIT = False
MAX_PARA_IN_A_PAGE = 100
RUN_WISE_PAGE_LIMIT = False
MAX_RUN_IN_A_PAGE = 30
WORD_WISE_PAGE_LIMIT = True
MAX_WORD_IN_A_PAGE = 500

# PPTX CONFIG
PPTX_PARAGRAPH_GEN = True
PPTX_TABLE_DATA_GEN = True
PPTX_TABLE_OF_CONTENT_GEN = False
PPTX_HEADER_FOOTER_GEN = False

PPTX_PARAGRAPH_TRANS = True
PPTX_TABLE_DATA_TRANS = True
PPTX_TABLE_OF_CONTENT_TRANS = False
PPTX_HEADER_FOOTER_TRANS = False

PPTX_HYPERLINK_SUPPORT = False
PPTX_PAGE_LIMIT_ENABLE = False

DOCX_FILE_PREFIX = 'DOCX-'
DOCX1_FILE_PREFIX = 'DOCX1-'
PPTX_FILE_PREFIX = 'PPTX-'
HTML_FILE_PREFIX = 'HTML-'
GENERATED_HTML_FILE_PATTERN = '.html'
GENERATED_PDF_FILE_PATTERN = '.pdf'
GENERATED_HTML_DEFAULT_NAME = 'document.html'

PUSH_GENERATED_HTML_TO_S3 = True

aws_access_key = os.environ.get('FT_AWS_S3_ACCESS_KEY', 'ACCESS_KEY')
aws_secret_key = os.environ.get('FT_AWS_S3_SECRET_KEY', 'SECRET_KEY')
aws_bucket_name = os.environ.get('FT_AWS_BUCKET_NAME', 'anuvaad1')
aws_link_prefix = f'https://{aws_bucket_name}.s3.amazonaws.com/'

ALLOWED_MIME_TYPES = ['application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                      'application/json',
                      'application/octet-stream',
                      'application/zip',
                      'text/html']
ALLOWED_FILE_EXTENSION = ['docx', 'pptx', 'json','html']

# FONT
ALLOWED_FONTS = {
    "hi": [
        "Akshar Unicode",
        "Amiko",
        "Amita",
        "Aparajita",
        "Arial Unicode MS",
        "Arya",
        "Asar",
        "Biryani",
        "Cambay",
        "Chandas",
        "Dekko",
        "Eczar",
        "Ek Mukta",
        "gargi",
        "GISTOT-BRXVinit",
        "GISTOT-DGRDhruv",
        "GIST-DVOTKishor",
        "GIST-DVOTMohini",
        "Glegoo",
        "Gotu",
        "Halant",
        "Hind",
        "Inknut Antiqua Black",
        "Inknut Antiqua",
        "Inknut Antiqua ExtraBold",
        "Inknut Antiqua Light",
        "Inknut Antiqua Medium",
        "Inknut Antiqua SemiBold",
        "Jaldi",
        "Kadwa",
        "Kalam",
        "Karma Regular",
        "Khand",
        "Khula",
        "Khula ExtraBold",
        "Khula Light",
        "Khula SemiBold",
        "Kokila",
        "Kurale",
        "Laila",
        "Lohit Devanagari",
        "Mangal",
        "Martel Heavy",
        "Martel",
        "Martel ExtraBold",
        "Martel UltraLight",
        "Martel Light",
        "Martel DemiBold",
        "Martel Sans Black",
        "Martel Sans",
        "Martel Sans ExtraBold",
        "Martel Sans ExtraLight",
        "Martel Sans Light",
        "Martel Sans SemiBold",
        "Modak",
        "Nakula",
        "Nirmala UI",
        "Nirmala UI Semilight",
        "Noto Sans Devanagari Bk",
        "Noto Sans Devanagari",
        "Noto Sans Devanagari Cn",
        "Noto Sans Devanagari Cn Bk",
        "Noto Sans Devanagari Cn XBd",
        "Noto Sans Devanagari Cn XLt",
        "Noto Sans Devanagari Cn Lt",
        "Noto Sans Devanagari Cn Md",
        "Noto Sans Devanagari Cn SmBd",
        "Noto Sans Devanagari Cn Th",
        "Noto Sans Devanagari XBd",
        "Noto Sans Devanagari XCn",
        "Noto Sans Devanagari XCn Bk",
        "Noto Sans Devanagari XCn XBd",
        "Noto Sans Devanagari XCn XLt",
        "Noto Sans Devanagari XCn Lt",
        "Noto Sans Devanagari XCn Md",
        "Noto Sans Devanagari XCn SmBd",
        "Noto Sans Devanagari XCn Th",
        "Noto Sans Devanagari XLt",
        "Noto Sans Devanagari Lt",
        "Noto Sans Devanagari Md",
        "Noto Sans Devanagari SmBd",
        "Noto Sans Devanagari SmCn",
        "Noto Sans Devanagari SmCn Bk",
        "Noto Sans Devanagari SmCn XBd",
        "Noto Sans Devanagari SmCn XLt",
        "Noto Sans Devanagari SmCn Lt",
        "Noto Sans Devanagari SmCn Md",
        "Noto Sans Devanagari SmCn SmBd",
        "Noto Sans Devanagari SmCn Th",
        "Noto Sans Devanagari Th",
        "Noto Sans Devanagari UI",
        "Noto Serif Devanagari",
        "Palanquin",
        "Palanquin ExtraLight",
        "Palanquin Light",
        "Palanquin Medium",
        "Palanquin SemiBold",
        "Palanquin Thin",
        "Palanquin Dark",
        "Palanquin Dark Medium",
        "Palanquin Dark SemiBold",
        "Poppins",
        "Pragati Narrow",
        "Rajdhani",
        "Ranga",
        "Rhodium Libre",
        "Rozha One",
        "Sahadeva",
        "Sahitya",
        "SakalBharati",
        "Samanata",
        "Samyak Devanagari",
        "Sanskrit Text",
        "Sanskrit 2003",
        "Sarai",
        "Sarala",
        "Sarpanch",
        "Siddhanta",
        "Sumana",
        "Sura",
        "Teko Regular",
        "Tillana",
        "Tillana ExtraBold",
        "Tillana Medium",
        "Tillana SemiBold",
        "Utsaah",
        "Vesper Libre Heavy",
        "Vesper Libre",
        "Vesper Libre Medium",
        "Yantramanav",
        "Yatra One"
    ],
    "kn": [
        "Akshar Unicode",
        "Arial Unicode MS",
        "Baloo Tamma",
        "Kedage",
        "Lohit Kannada",
        "Mallige",
        "Nirmala UI",
        "Nirmala UI Semilight",
        "Noto Sans Kannada",
        "Noto Sans Kannada UI",
        "Noto Serif Kannada",
        "Tunga"
    ],
    "gu": [
        "aakar",
        "Arial Unicode MS",
        "Baloo Bhai",
        "Lohit Gujarati",
        "Mogra",
        "Nirmala UI",
        "Nirmala UI Semilight",
        "Noto Sans Gujarati",
        "Noto Sans Gujarati UI",
        "Noto Serif Gujarati",
        "padmaa",
        "padmaa-Bold.1.1",
        "Rasa",
        "Rekha",
        "Samyak Gujarati",
        "Shruti"
    ],
    "ta": [
        "Arima Madurai Black",
        "Arima Madurai",
        "Arima Madurai ExtraBold",
        "Arima Madurai ExtraLight",
        "Arima Madurai Light",
        "Arima Madurai Medium",
        "Arima Madurai Thin",
        "Baloo Thambi 2",
        "Baloo Thambi 2 ExtraBold",
        "Baloo Thambi 2 Medium",
        "Baloo Thambi 2 SemiBold",
        "Catamaran Black",
        "Catamaran",
        "Catamaran ExtraBold",
        "Catamaran ExtraLight",
        "Catamaran Light",
        "Catamaran Medium",
        "Catamaran SemiBold",
        "Catamaran Thin",
        "Coiny",
        "Hind Madurai",
        "Hind Madurai Light",
        "Hind Madurai Medium",
        "Hind Madurai SemiBold",
        "Kavivanar",
        "Latha",
        "Meera Inimai",
        "Mukta Malar",
        "Mukta Malar ExtraBold",
        "Mukta Malar ExtraLight",
        "Mukta Malar Light",
        "Mukta Malar Medium",
        "Mukta Malar SemiBold",
        "Nirmala UI",
        "Nirmala UI Semilight",
        "Noto Sans Tamil Blk",
        "Noto Sans Tamil",
        "Noto Sans Tamil Cond",
        "Noto Sans Tamil Cond Blk",
        "Noto Sans Tamil Cond ExtBd",
        "Noto Sans Tamil Cond ExtLt",
        "Noto Sans Tamil Cond Light",
        "Noto Sans Tamil Cond Med",
        "Noto Sans Tamil Cond SemBd",
        "Noto Sans Tamil Cond Thin",
        "Noto Sans Tamil ExtBd",
        "Noto Sans Tamil ExtCond",
        "Noto Sans Tamil ExtCond Blk",
        "Noto Sans Tamil ExtCond ExtBd",
        "Noto Sans Tamil ExtCond ExtLt",
        "Noto Sans Tamil ExtCond Light",
        "Noto Sans Tamil ExtCond Med",
        "Noto Sans Tamil ExtCond SemBd",
        "Noto Sans Tamil ExtCond Thin",
        "Noto Sans Tamil ExtLt",
        "Noto Sans Tamil Light",
        "Noto Sans Tamil Med",
        "Noto Sans Tamil SemBd",
        "Noto Sans Tamil SemCond",
        "Noto Sans Tamil SemCond Blk",
        "Noto Sans Tamil SemCond ExtBd",
        "Noto Sans Tamil SemCond ExtLt",
        "Noto Sans Tamil SemCond Light",
        "Noto Sans Tamil SemCond Med",
        "Noto Sans Tamil SemCond SemBd",
        "Noto Sans Tamil SemCond Thin",
        "Noto Sans Tamil Thin",
        "Noto Sans Tamil UI",
        "Noto Serif Tamil Blk",
        "Noto Serif Tamil",
        "Noto Serif Tamil Cond",
        "Noto Serif Tamil Cond Blk",
        "Noto Serif Tamil Cond ExtBd",
        "Noto Serif Tamil Cond ExtLt",
        "Noto Serif Tamil Cond Light",
        "Noto Serif Tamil Cond Med",
        "Noto Serif Tamil Cond SemBd",
        "Noto Serif Tamil Cond Thin",
        "Noto Serif Tamil ExtBd",
        "Noto Serif Tamil ExtCond",
        "Noto Serif Tamil ExtCond Blk",
        "Noto Serif Tamil ExtCond ExtBd",
        "Noto Serif Tamil ExtCond ExtLt",
        "Noto Serif Tamil ExtCond Light",
        "Noto Serif Tamil ExtCond Med",
        "Noto Serif Tamil ExtCond SemBd",
        "Noto Serif Tamil ExtCond Thin",
        "Noto Serif Tamil ExtLt",
        "Noto Serif Tamil Light",
        "Noto Serif Tamil Med",
        "Noto Serif Tamil SemBd",
        "Noto Serif Tamil SemCond",
        "Noto Serif Tamil SemCond Blk",
        "Noto Serif Tamil SemCond ExtBd",
        "Noto Serif Tamil SemCond ExtLt",
        "Noto Serif Tamil SemCond Light",
        "Noto Serif Tamil SemCond Med",
        "Noto Serif Tamil SemCond SemBd",
        "Noto Serif Tamil SemCond Thin",
        "Noto Serif Tamil Thin",
        "Pavanam",
        "SUNDARAM-0806",
        "SUNDARAM-0807",
        "SUNDARAM-0808",
        "SUNDARAM-0810",
        "SUNDARAM-0812",
        "SUNDARAM-0819",
        "SUNDARAM-0820",
        "SUNDARAM-0821",
        "SUNDARAM-0823",
        "SUNDARAM-0824",
        "SUNDARAM-0827",
        "SUNDARAM-0830",
        "SUNDARAM-0831",
        "SUNDARAM-1341",
        "SUNDARAM-1342",
        "SUNDARAM-1351",
        "SUNDARAM-1352",
        "SUNDARAM-2852",
        "SUNDARAM-2865",
        "SUNDARAM-3811",
        "TAU_Elango_Abirami",
        "TAU_Elango_Agasthiyar",
        "TAU_Elango_Anjali",
        "TAU_Elango_Arunthathi",
        "TAU_Elango_Asokan",
        "TAU_Elango_Athithan",
        "TAU_Elango_Barathi",
        "TAU_Elango_Bhoopalam",
        "TAU_Elango_Cheran",
        "TAU_Elango_Cholaa",
        "TAU_Elango_Devi",
        "TAU_Elango_Dhanam",
        "TAU_Elango_Ganga",
        "TAU_Elango_Godavari",
        "TAU_Elango_Guntalakesi",
        "TAU_Elango_Janani",
        "TAU_Elango_Juliee",
        "TAU_Elango_Kabini",
        "TAU_Elango_Kalyani",
        "TAU_Elango_Kamban",
        "TAU_Elango_Kannagi",
        "TAU_Elango_Kapilan",
        "TAU_Elango_Krishna",
        "TAU_Elango_Madhavi",
        "TAU_Elango_Malyamar",
        "TAU_Elango_Manimekalai",
        "TAU_Elango_Marutham",
        "TAU_Elango_Mohanam",
        "TAU_Elango_Mullai",
        "TAU_Elango_Muthu",
        "TAU_Elango_Nalina",
        "TAU_Elango_Neelampari",
        "TAU_Elango_Pallavi",
        "TAU_Elango_Panchali",
        "TAU_Elango_Pavalam",
        "TAU_Elango_Priyanka",
        "TAU_Elango_Ragham",
        "TAU_Elango_Rathnam",
        "TAU_Elango_Rewathy",
        "TAU_Elango_Sabari",
        "TAU_Elango_Sankara",
        "TAU_Elango_Senguttuvan",
        "TAU_Elango_Surya",
        "TAU_Elango_Themmangu",
        "TAU_Elango_Thilllana",
        "TAU_Elango_Todi",
        "TAU_Elango_Vairam",
        "TAU_Elango_Valluvan",
        "TAU_Elango_Vasuki",
        "TAU_Elango_Veena",
        "Vijaya",
        "Mcl Uzhavan",
        "Mcl bharathi"
    ],
    "bn": [
        "AdorshoLipi",
        "Akaash",
        "AponaLohit",
        "Arial Unicode MS",
        "Atma",
        "Atma Medium",
        "Atma Light",
        "Atma SemiBold",
        "Bangla",
        "BenSen",
        "BenSenHandwriting",
        "Charukola Round Head Unicode",
        "CharuChandan HardStroke Unicode",
        "Charukola Unicode",
        "Charu Chandan 3D Unicode",
        "Charu Chandan Unicode",
        "Ekushey Azad",
        "Ekushey Durga",
        "Ekushey Godhuli",
        "Ekushey Lohit",
        "Ekushey Mohua",
        "Ekushey Puja",
        "Ekushey Punarbhaba",
        "Ekushey Saraswatii",
        "Ekushey Sharifa",
        "Ekushey Sumit",
        "Fazlay Sejuti Unicode",
        "Galada",
        "Hind Siliguri",
        "Hind Siliguri Light",
        "Hind Siliguri Medium",
        "Hind Siliguri SemiBold",
        "Kalpurush",
        "Mina",
        "Mitra Mono",
        "Mukti",
        "MuktiNarrow",
        "Nikosh",
        "NikoshBAN",
        "NikoshGrameem",
        "NikoshLight",
        "NikoshLightBAN",
        "Nirmala UI",
        "Nirmala UI Semilight",
        "Noto Sans Bengali Blk",
        "Noto Sans Bengali",
        "Noto Sans Bengali ExtBd",
        "Noto Sans Bengali ExtLt",
        "Noto Sans Bengali Light",
        "Noto Sans Bengali Med",
        "Noto Sans Bengali SemBd",
        "Noto Sans Bengali Thin",
        "Noto Sans Bengali UI",
        "Noto Serif Bengali",
        "Sagar",
        "Shorif Shishir Unicode",
        "Siyam Rupali",
        "SolaimanLipi"
    ],
    "te": [
        "Akaya Telivigala",
        "Arial Unicode MS",
        "Baloo Tammudu 2",
        "Baloo Tammudu 2 ExtraBold",
        "Baloo Tammudu 2 Medium",
        "Baloo Tammudu 2 SemiBold",
        "Chathura",
        "Chathura ExtraBold",
        "Chathura Light",
        "Chathura Thin",
        "Dhurjati",
        "Gidugu",
        "Gurajada",
        "Hind Guntur",
        "Hind Guntur Light",
        "Hind Guntur Medium",
        "Hind Guntur SemiBold",
        "Lakki Reddy",
        "LakkiReddy",
        "Mallanna",
        "Mandali",
        "NATS",
        "Nirmala UI",
        "Nirmala UI Semilight",
        "Noto Sans Telugu",
        "Noto Sans Telugu UI",
        "Noto Serif Telugu",
        "NTR",
        "Peddana",
        "Ponnala",
        "Ramabhadra",
        "Ramaraja",
        "Ravi Prakash",
        "RaviPrakash",
        "Sree Krushnadevaraya",
        "Suranna",
        "Suravaram",
        "Tenali Ramakrishna",
        "Timmana"
    ],
    "ml": [
        "Akshar Unicode",
        "Arial Unicode MS",
        "Baloo Chettan 2",
        "Baloo Chettan 2 ExtraBold",
        "Baloo Chettan 2 Medium",
        "Baloo Chettan 2 SemiBold",
        "Chilanka",
        "Gayathri",
        "Gayathri Thin",
        "Kartika",
        "Manjari",
        "Manjari Thin",
        "Meera",
        "Nellu",
        "Nirmala UI",
        "Nirmala UI Semilight",
        "Noto Sans Malayalam",
        "Noto Sans Malayalam UI",
        "Noto Serif Malayalam",
        "Uroob"
    ],
    "mr": [
        "Akshar Unicode",
        "Amiko",
        "Amita",
        "Aparajita",
        "Arial Unicode MS",
        "Arya",
        "Asar",
        "Biryani",
        "Cambay",
        "Chandas",
        "Dekko",
        "Eczar",
        "Ek Mukta",
        "gargi",
        "GISTOT-BRXVinit",
        "GISTOT-DGRDhruv",
        "GIST-DVOTKishor",
        "GIST-DVOTMohini",
        "Glegoo",
        "Gotu",
        "Halant",
        "Hind",
        "Inknut Antiqua Black",
        "Inknut Antiqua",
        "Inknut Antiqua ExtraBold",
        "Inknut Antiqua Light",
        "Inknut Antiqua Medium",
        "Inknut Antiqua SemiBold",
        "Jaldi",
        "Kadwa",
        "Kalam",
        "Karma Regular",
        "Khand",
        "Khula",
        "Khula ExtraBold",
        "Khula Light",
        "Khula SemiBold",
        "Kokila",
        "Kurale",
        "Laila",
        "Lohit Devanagari",
        "Mangal",
        "Martel Heavy",
        "Martel",
        "Martel ExtraBold",
        "Martel UltraLight",
        "Martel Light",
        "Martel DemiBold",
        "Martel Sans Black",
        "Martel Sans",
        "Martel Sans ExtraBold",
        "Martel Sans ExtraLight",
        "Martel Sans Light",
        "Martel Sans SemiBold",
        "Modak",
        "Nakula",
        "Nirmala UI",
        "Nirmala UI Semilight",
        "Noto Sans Devanagari Bk",
        "Noto Sans Devanagari",
        "Noto Sans Devanagari Cn",
        "Noto Sans Devanagari Cn Bk",
        "Noto Sans Devanagari Cn XBd",
        "Noto Sans Devanagari Cn XLt",
        "Noto Sans Devanagari Cn Lt",
        "Noto Sans Devanagari Cn Md",
        "Noto Sans Devanagari Cn SmBd",
        "Noto Sans Devanagari Cn Th",
        "Noto Sans Devanagari XBd",
        "Noto Sans Devanagari XCn",
        "Noto Sans Devanagari XCn Bk",
        "Noto Sans Devanagari XCn XBd",
        "Noto Sans Devanagari XCn XLt",
        "Noto Sans Devanagari XCn Lt",
        "Noto Sans Devanagari XCn Md",
        "Noto Sans Devanagari XCn SmBd",
        "Noto Sans Devanagari XCn Th",
        "Noto Sans Devanagari XLt",
        "Noto Sans Devanagari Lt",
        "Noto Sans Devanagari Md",
        "Noto Sans Devanagari SmBd",
        "Noto Sans Devanagari SmCn",
        "Noto Sans Devanagari SmCn Bk",
        "Noto Sans Devanagari SmCn XBd",
        "Noto Sans Devanagari SmCn XLt",
        "Noto Sans Devanagari SmCn Lt",
        "Noto Sans Devanagari SmCn Md",
        "Noto Sans Devanagari SmCn SmBd",
        "Noto Sans Devanagari SmCn Th",
        "Noto Sans Devanagari Th",
        "Noto Sans Devanagari UI",
        "Noto Serif Devanagari",
        "Palanquin",
        "Palanquin ExtraLight",
        "Palanquin Light",
        "Palanquin Medium",
        "Palanquin SemiBold",
        "Palanquin Thin",
        "Palanquin Dark",
        "Palanquin Dark Medium",
        "Palanquin Dark SemiBold",
        "Poppins",
        "Pragati Narrow",
        "Rajdhani",
        "Ranga",
        "Rhodium Libre",
        "Rozha One",
        "Sahadeva",
        "Sahitya",
        "SakalBharati",
        "Samanata",
        "Samyak Devanagari",
        "Sanskrit Text",
        "Sanskrit 2003",
        "Sarai",
        "Sarala",
        "Sarpanch",
        "Siddhanta",
        "Sumana",
        "Sura",
        "Teko Regular",
        "Tillana",
        "Tillana ExtraBold",
        "Tillana Medium",
        "Tillana SemiBold",
        "Utsaah",
        "Vesper Libre Heavy",
        "Vesper Libre",
        "Vesper Libre Medium",
        "Yantramanav",
        "Yatra One"
    ],
    "pa": [
        "GHW Adhiapak 4 Book",
        "Arial Unicode MS",
        "Baloo Paaji 2",
        "Baloo Paaji 2 ExtraBold",
        "Baloo Paaji 2 Medium",
        "Baloo Paaji 2 SemiBold",
        "Bulara Thin Border",
        "Bulara Hollow",
        "Bulara Hollow Bold",
        "Bulara Thin Border Outline",
        "Bulara Thin Border Body",
        "Bulara",
        "Bulara Demi-Bold",
        "Bulara Heavy",
        "Bulara Black",
        "Choti Script 7 Bold",
        "GHW Adhiapak Chisel 9 Blk",
        "GHW Adhiapak Mark 5 Med",
        "GHW Adhiapak Mark 9 Blk",
        "GHW Adhiapak Mark 5 Med Tip",
        "GHW Adhiapak Mark 9 Blk Tip",
        "GHW Adhiapak 1 Thin",
        "GHW Adhiapak 2 Extra Light",
        "GHW Adhiapak 3 Light",
        "GHW Adhiapak 5 Medium",
        "GHW Adhiapak 6 Demi-Bold",
        "GHW Adhiapak 7 Bold",
        "GHW Adhiapak 8 Heavy",
        "GHW Adhiapak 9 Black",
        "GHW Dukandar Marker Bold Tips",
        "GHW Dukandar Marker",
        "GHW Dukandar Marker Bold",
        "GHW Dukandar",
        "GHW Dukandar Bold",
        "Gurvetica 00 Slight Ultra-Thin",
        "Gurvetica 01 Slight Thin",
        "Gurvetica 02 Slight Extra-Light",
        "Gurvetica 03 Slight Light",
        "Gurvetica 10 Ult-Cond Ult-Thin",
        "Gurvetica 12 Ultra Con Ext Lit",
        "Gurvetica 14 Ultra Condensed Book",
        "Gurvetica 15 Ultra Cond Medium",
        "Gurvetica 16 Ult-Con Dem-Bold",
        "Gurvetica 24 Extra Cond Book",
        "Gurvetica 27 Extra Cond Bold",
        "Gurvetica 28 Extra Cond Bold",
        "Gurvetica 30 Condensed UltThn",
        "Gurvetica 32 Cond ExtLight",
        "Gurvetica 34 Condensed Book",
        "Gurvetica 37 Condensed Bold",
        "Gurvetica 39 Condensed Black",
        "Gurvetica 44 SemCond Book",
        "Gurvetica 47 SemCond Bold",
        "Gurvetica 49 SemCond Black",
        "Gurvetica 50 Medium Ultra Thin",
        "Gurvetica 51 Medium Thin",
        "Gurvetica 52 Medium Extra-Light",
        "Gurvetica 53 Medium Light",
        "Gurvetica 54 Medium Book",
        "Gurvetica 55 Medium Medium",
        "Gurvetica 56 Medium Demi-Bold",
        "Gurvetica 57 Medium Bold",
        "Gurvetica 58 Medium Heavy",
        "Gurvetica 59 Medium Black",
        "Gurvetica 64 SemiExp Book",
        "Gurvetica 65 SemiExp Medium",
        "Gurvetica 67 SemiExp Bold",
        "Gurvetica 69 SemiExp Black",
        "Gurvetica 70 Exp Ultra Thin",
        "Gurvetica 72 Exp Extra-Light",
        "Gurvetica 74 Expanded Book",
        "Gurvetica 77 Expanded Bold",
        "Gurvetica 79 Expanded Black",
        "Gurvetica 84 Extra Exp Book",
        "Gurvetica 87 Extra Exp Bold",
        "Gurvetica 89 Extra Exp Black",
        "Gurvetica 90 Ultra Exp UltThin",
        "Gurvetica 92 Ult Exp ExLight",
        "Gurvetica 93 Ultra Expanded Light",
        "Gurvetica 94 Ultra Exp Book",
        "Gurvetica 97 Ultra Expanded Bold",
        "Gurvetica 99 Ultra Exp Black",
        "Karmic Sanj Thin",
        "Karmic Sanj Light",
        "Karmic Sanj Book",
        "Karmic Sanj Medium",
        "Karmic Sanj Bold",
        "Karmic Sanj Heavy",
        "Karmic Sanj Black",
        "Langar",
        "Lanma Script 3 Light",
        "Lanma Script 5 Medium",
        "Magaz Thin",
        "Magaz Light",
        "Magaz",
        "Magaz Bold",
        "Magaz Black",
        "Mukta Mahee",
        "Mukta Mahee ExtraBold",
        "Mukta Mahee ExtraLight",
        "Mukta Mahee Light",
        "Mukta Mahee Medium",
        "Mukta Mahee SemiBold",
        "Nirmala UI",
        "Nirmala UI Semilight",
        "Noto Sans Gurmukhi",
        "Noto Sans Gurmukhi UI",
        "Punjabi Typewriter",
        "Punjabi Typewriter Engraved",
        "Punjabi Typewriter Old",
        "Raajaa Script 2 Thin",
        "Raajaa Script 5 Medium",
        "Raajaa 1 Thin",
        "Raajaa 3 Light",
        "Raajaa 5 Medium",
        "Raajaa 7 Bold",
        "Raajaa 9 Black",
        "Raaj Script 2 Thin",
        "Raaj Script 5 Medium",
        "Raaj 1 Thin",
        "Raaj 3 Light",
        "Raaj 5 Medium",
        "Raaj 7 Bold",
        "Raaj 9 Black",
        "Rupe Outline 2 Extra Light",
        "Rupe Outline 3 Light",
        "Rupe Outline 4 Book",
        "Rupe Outline 5 Medium",
        "Rupe Outline 6 Demi Bold",
        "Rupe Outline 7 Bold",
        "Rupe Outline 8 Heavy",
        "Rupe Outline 9 Black",
        "Rupe Border 6 Demi Bold",
        "Rupe Border 7 Bold",
        "Rupe Border 8 Heavy",
        "Rupe Border 9 Black",
        "Rupe 0 Ultra Thin",
        "Rupe 1 Thin",
        "Rupe 2 Extra Light",
        "Rupe 3 Light",
        "Rupe 4 Book",
        "Rupe 5 Medium",
        "Rupe 6 Demi Bold",
        "Rupe 7 Bold",
        "Rupe 8 Heavy",
        "Rupe 9 Black"
    ],
    "common": [
        "Agency FB",
        "Alef",
        "Algerian",
        "Amiri",
        "Book Antiqua",
        "Arial Unicode MS",
        "Arial",
        "Arial Narrow",
        "Arial Black",
        "Arial Rounded MT Bold",
        "Bahnschrift",
        "Baskerville Old Face",
        "Bauhaus 93",
        "Bell MT",
        "Bernard MT Condensed",
        "Bodoni MT",
        "Bodoni MT Black",
        "Bodoni MT Condensed",
        "Bodoni MT Poster Compressed",
        "Bookman Old Style",
        "Bradley Hand ITC",
        "Britannic Bold",
        "Berlin Sans FB",
        "Berlin Sans FB Demi",
        "Broadway",
        "Brush Script MT",
        "Caladea",
        "Calibri",
        "Calibri Light",
        "Californian FB",
        "Calisto MT",
        "Cambria",
        "Candara",
        "Candara Light",
        "Carlito",
        "Castellar",
        "Century Schoolbook",
        "Centaur",
        "Century",
        "Chiller",
        "Colonna MT",
        "Comic Sans MS",
        "Consolas",
        "Constantia",
        "Cooper Black",
        "Copperplate Gothic Bold",
        "Copperplate Gothic Light",
        "Corbel",
        "Corbel Light",
        "Courier New",
        "Curlz MT",
        "David CLM",
        "David Libre",
        "DejaVu Math TeX Gyre",
        "DejaVu Sans",
        "DejaVu Sans Light",
        "DejaVu Sans Condensed",
        "DejaVu Sans Mono",
        "DejaVu Serif",
        "DejaVu Serif Condensed",
        "DevLys 010",
        "Dubai",
        "Dubai Light",
        "Dubai Medium",
        "Ebrima",
        "Elephant",
        "Engravers MT",
        "Eras Bold ITC",
        "Eras Demi ITC",
        "Eras Light ITC",
        "Eras Medium ITC",
        "Felix Titling",
        "Forte",
        "Franklin Gothic Book",
        "Franklin Gothic Demi",
        "Franklin Gothic Demi Cond",
        "Franklin Gothic Heavy",
        "Franklin Gothic Medium",
        "Franklin Gothic Medium Cond",
        "Frank Ruehl CLM",
        "Freestyle Script",
        "French Script MT",
        "Footlight MT Light",
        "Gabriola",
        "Gadugi",
        "Garamond",
        "Gentium Basic",
        "Gentium Book Basic",
        "Georgia",
        "Gigi",
        "Gill Sans MT",
        "Gill Sans MT Condensed",
        "Gill Sans Ultra Bold Condensed",
        "Gill Sans Ultra Bold",
        "Gloucester MT Extra Condensed",
        "Gill Sans MT Ext Condensed Bold",
        "Century Gothic",
        "Goudy Old Style",
        "Goudy Stout",
        "Harlow Solid Italic",
        "Harrington",
        "Haettenschweiler",
        "Microsoft Himalaya",
        "High Tower Text",
        "Impact",
        "Imprint MT Shadow",
        "Informal Roman",
        "Ink Free",
        "Blackadder ITC",
        "Edwardian Script ITC",
        "Kristen ITC",
        "Javanese Text",
        "Jokerman",
        "Juice ITC",
        "Kunstler Script",
        "Wide Latin",
        "Lucida Bright",
        "Lucida Calligraphy",
        "Leelawadee UI",
        "Leelawadee",
        "Leelawadee UI Semilight",
        "Lucida Fax",
        "Lucida Handwriting",
        "Liberation Mono",
        "Liberation Sans",
        "Liberation Sans Narrow",
        "Liberation Serif",
        "Linux Biolinum G",
        "Linux Libertine Display G",
        "Linux Libertine G",
        "Lucida Sans",
        "Lucida Sans Typewriter",
        "Lucida Console",
        "Lucida Sans Unicode",
        "Magneto",
        "Maiandra GD",
        "Malgun Gothic",
        "Malgun Gothic Semilight",
        "Matura MT Script Capitals",
        "Microsoft Sans Serif",
        "Miriam Mono CLM",
        "Mistral",
        "Myanmar Text",
        "Modern No. 20",
        "Mongolian Baiti",
        "Microsoft Uighur",
        "Microsoft Yi Baiti",
        "Monotype Corsiva",
        "MV Boli",
        "Niagara Engraved",
        "Niagara Solid",
        "Nirmala UI",
        "Nirmala UI Semilight",
        "Noto Mono",
        "Noto Sans Blk",
        "Noto Sans",
        "Noto Sans Cond",
        "Noto Sans Cond Blk",
        "Noto Sans Cond ExtBd",
        "Noto Sans Cond ExtLt",
        "Noto Sans Cond Light",
        "Noto Sans Cond Med",
        "Noto Sans Cond SemBd",
        "Noto Sans Cond Thin",
        "Noto Sans ExtBd",
        "Noto Sans ExtCond",
        "Noto Sans ExtCond Blk",
        "Noto Sans ExtCond ExtBd",
        "Noto Sans ExtCond ExtLt",
        "Noto Sans ExtCond Light",
        "Noto Sans ExtCond Med",
        "Noto Sans ExtCond SemBd",
        "Noto Sans ExtCond Thin",
        "Noto Sans ExtLt",
        "Noto Sans Light",
        "Noto Sans Med",
        "Noto Sans SemBd",
        "Noto Sans SemCond",
        "Noto Sans SemCond Blk",
        "Noto Sans SemCond ExtBd",
        "Noto Sans SemCond ExtLt",
        "Noto Sans SemCond Light",
        "Noto Sans SemCond Med",
        "Noto Sans SemCond SemBd",
        "Noto Sans SemCond Thin",
        "Noto Sans Thin",
        "Noto Sans Disp Blk",
        "Noto Sans Disp",
        "Noto Sans Disp Cond",
        "Noto Sans Disp Cond Blk",
        "Noto Sans Disp Cond ExtBd",
        "Noto Sans Disp Cond ExtLt",
        "Noto Sans Disp Cond Light",
        "Noto Sans Disp Cond Med",
        "Noto Sans Disp Cond SemBd",
        "Noto Sans Disp Cond Thin",
        "Noto Sans Disp ExtBd",
        "Noto Sans Disp ExtCond",
        "Noto Sans Disp ExtCond Blk",
        "Noto Sans Disp ExtCond ExtBd",
        "Noto Sans Disp ExtCond ExtLt",
        "Noto Sans Disp ExtCond Light",
        "Noto Sans Disp ExtCond Med",
        "Noto Sans Disp ExtCond SemBd",
        "Noto Sans Disp ExtCond Thin",
        "Noto Sans Disp ExtLt",
        "Noto Sans Disp Light",
        "Noto Sans Disp Med",
        "Noto Sans Disp SemBd",
        "Noto Sans Disp SemCond",
        "Noto Sans Disp SemCond Blk",
        "Noto Sans Disp SemCond ExtBd",
        "Noto Sans Disp SemCond ExtLt",
        "Noto Sans Disp SemCond Light",
        "Noto Sans Disp SemCond Med",
        "Noto Sans Disp SemCond SemBd",
        "Noto Sans Disp SemCond Thin",
        "Noto Sans Disp Thin",
        "Noto Sans Mono Blk",
        "Noto Sans Mono",
        "Noto Sans Mono Cond",
        "Noto Sans Mono Cond Blk",
        "Noto Sans Mono Cond ExtBd",
        "Noto Sans Mono Cond ExtLt",
        "Noto Sans Mono Cond Light",
        "Noto Sans Mono Cond Med",
        "Noto Sans Mono Cond SemBd",
        "Noto Sans Mono Cond Thin",
        "Noto Sans Mono ExtBd",
        "Noto Sans Mono ExtCond",
        "Noto Sans Mono ExtCond Blk",
        "Noto Sans Mono ExtCond ExtBd",
        "Noto Sans Mono ExtCond ExtLt",
        "Noto Sans Mono ExtCond Light",
        "Noto Sans Mono ExtCond Med",
        "Noto Sans Mono ExtCond SemBd",
        "Noto Sans Mono ExtCond Thin",
        "Noto Sans Mono ExtLt",
        "Noto Sans Mono Light",
        "Noto Sans Mono Med",
        "Noto Sans Mono SemBd",
        "Noto Sans Mono SemCond",
        "Noto Sans Mono SemCond Blk",
        "Noto Sans Mono SemCond ExtBd",
        "Noto Sans Mono SemCond ExtLt",
        "Noto Sans Mono SemCond Light",
        "Noto Sans Mono SemCond Med",
        "Noto Sans Mono SemCond SemBd",
        "Noto Sans Mono SemCond Thin",
        "Noto Sans Mono Thin",
        "Noto Sans Symbols Blk",
        "Noto Sans Symbols",
        "Noto Sans Symbols ExtBd",
        "Noto Sans Symbols ExtLt",
        "Noto Sans Symbols Light",
        "Noto Sans Symbols Med",
        "Noto Sans Symbols SemBd",
        "Noto Sans Symbols Thin",
        "Noto Serif Blk",
        "Noto Serif",
        "Noto Serif Cond",
        "Noto Serif Cond Blk",
        "Noto Serif Cond ExtBd",
        "Noto Serif Cond ExtLt",
        "Noto Serif Cond Light",
        "Noto Serif Cond Med",
        "Noto Serif Cond SemBd",
        "Noto Serif Cond Thin",
        "Noto Serif ExtBd",
        "Noto Serif ExtCond",
        "Noto Serif ExtCond Blk",
        "Noto Serif ExtCond ExtBd",
        "Noto Serif ExtCond ExtLt",
        "Noto Serif ExtCond Light",
        "Noto Serif ExtCond Med",
        "Noto Serif ExtCond SemBd",
        "Noto Serif ExtCond Thin",
        "Noto Serif ExtLt",
        "Noto Serif Light",
        "Noto Serif Med",
        "Noto Serif SemBd",
        "Noto Serif SemCond",
        "Noto Serif SemCond Blk",
        "Noto Serif SemCond ExtBd",
        "Noto Serif SemCond ExtLt",
        "Noto Serif SemCond Light",
        "Noto Serif SemCond Med",
        "Noto Serif SemCond SemBd",
        "Noto Serif SemCond Thin",
        "Noto Serif Thin",
        "Noto Serif Disp Blk",
        "Noto Serif Disp",
        "Noto Serif Disp Cond",
        "Noto Serif Disp Cond Blk",
        "Noto Serif Disp Cond ExtBd",
        "Noto Serif Disp Cond ExtLt",
        "Noto Serif Disp Cond Light",
        "Noto Serif Disp Cond Med",
        "Noto Serif Disp Cond SemBd",
        "Noto Serif Disp Cond Thin",
        "Noto Serif Disp ExtBd",
        "Noto Serif Disp ExtCond",
        "Noto Serif Disp ExtCond Blk",
        "Noto Serif Disp ExtCond ExtBd",
        "Noto Serif Disp ExtCond ExtLt",
        "Noto Serif Disp ExtCond Light",
        "Noto Serif Disp ExtCond Med",
        "Noto Serif Disp ExtCond SemBd",
        "Noto Serif Disp ExtCond Thin",
        "Noto Serif Disp ExtLt",
        "Noto Serif Disp Light",
        "Noto Serif Disp Med",
        "Noto Serif Disp SemBd",
        "Noto Serif Disp SemCond",
        "Noto Serif Disp SemCond Blk",
        "Noto Serif Disp SemCond ExtBd",
        "Noto Serif Disp SemCond ExtLt",
        "Noto Serif Disp SemCond Light",
        "Noto Serif Disp SemCond Med",
        "Noto Serif Disp SemCond SemBd",
        "Noto Serif Disp SemCond Thin",
        "Noto Serif Disp Thin",
        "Microsoft New Tai Lue",
        "Nunito Black",
        "Nunito",
        "Nunito ExtraBold",
        "Nunito ExtraLight",
        "Nunito Light",
        "Nunito SemiBold",
        "OCR A Extended",
        "Old English Text MT",
        "Onyx",
        "Palatino Linotype",
        "Palace Script MT",
        "Papyrus",
        "Parchment",
        "Perpetua",
        "Perpetua Titling MT",
        "Microsoft PhagsPa",
        "Playbill",
        "Poor Richard",
        "Pristina",
        "Rage Italic",
        "Ravie",
        "Reem Kufi",
        "MS Reference Sans Serif",
        "MS Reference Specialty",
        "Rockwell Condensed",
        "Rockwell",
        "Rockwell Extra Bold",
        "Rubik",
        "Scheherazade",
        "Script MT Bold",
        "Segoe Print",
        "Segoe Script",
        "Segoe UI",
        "Segoe UI Light",
        "Segoe UI Semilight",
        "Segoe UI Black",
        "Segoe UI Emoji",
        "Segoe UI Historic",
        "Segoe UI Semibold",
        "Segoe UI Symbol",
        "Showcard Gothic",
        "SimSun-ExtB",
        "Snap ITC",
        "Source Code Pro Black",
        "Source Code Pro",
        "Source Code Pro ExtraLight",
        "Source Code Pro Light",
        "Source Code Pro Medium",
        "Source Code Pro Semibold",
        "Source Sans Pro Black",
        "Source Sans Pro",
        "Source Sans Pro ExtraLight",
        "Source Sans Pro Light",
        "Source Sans Pro Semibold",
        "Source Serif Pro Black",
        "Source Serif Pro",
        "Source Serif Pro ExtraLight",
        "Source Serif Pro Light",
        "Source Serif Pro Semibold",
        "Stencil",
        "Sylfaen",
        "Symbol",
        "Tahoma",
        "Microsoft Tai Le",
        "Tw Cen MT",
        "Tw Cen MT Condensed",
        "Tw Cen MT Condensed Extra Bold",
        "Tempus Sans ITC",
        "Times New Roman",
        "Trebuchet MS",
        "Verdana",
        "Viner Hand ITC",
        "Vivaldi",
        "Vladimir Script",
        "Webdings",
        "Wingdings",
        "Wingdings 2",
        "Wingdings 3"
    ]
}


logging.basicConfig(
    filename=os.getenv("SERVICE_LOG", "server.log"),
    level=logging.DEBUG,
    format="%(levelname)s: %(asctime)s \
        pid:%(process)s module:%(module)s %(message)s",
    datefmt="%d/%m/%y %H:%M:%S",
)
