const sentence_actions = {
    SENTENCE_MERGED: 'SENTENCE_MERGED',
    SENTENCE_SPLITTED: 'SENTENCE_SPLITTED',
    SENTENCE_SAVED: 'SENTENCE_SAVED',
    START_MODE_MERGE: 'START_MODE_MERGE',
    END_MODE_MERGE: 'END_MODE_MERGE',
    SENTENCE_SOURCE_EDITED: 'SENTENCE_SOURCE_EDITED',
    ADD_SENTENCE_FOR_MERGE: 'ADD_SENTENCE_FOR_MERGE',
    REMOVE_SENTENCE_FOR_MERGE: 'REMOVE_SENTENCE_FOR_MERGE',
    RETRANSLATE_SENTENCE: 'RETRANSLATE_SENTENCE'
};
export default sentence_actions;